title: Tomasz Gelo
description: My Personal Blog
author: Tomasz Gelo
logo: /static/img/profile2.jpg
github: https://github.com/tgelo
about: JVM developer

baseurl: ""
url: "https://codeasashu.github.io/hcz-jekyll-blog"

disqus_shortname: aboutashu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 10
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
